### PR TITLE
Fixing mailcatcher upstart script

### LINKED ISSUE #430: Mailcatcher not sending emails
I just tried sending an email with PHP but it times out if mailcatcher is installed, I think there's an extra `'` character in the IP here: https://github.com/fideloper/Vaprobash/blob/master/scripts/mailcatcher.sh#L39

However I fixed it and it doesn't look like that's the problem, it seems that the issue is related to the `--foreground` flag, if I keep it then the mailcatcher script hangs when it reaches [this point](https://github.com/fideloper/Vaprobash/blob/master/scripts/mailcatcher.sh#L39) but if I remove it then outgoing emails don't work. I removed the flag during provisioning and ran `mailcatcher --foreground --http-ip=0.0.0.0` after it was finished and everything worked as expected.

PS: Most likely related to [this issue](https://github.com/sj26/mailcatcher/issues/182) in the mailcatcher repo

### PR DESCRIPTION
**Pull request by badams**
Fixes  #430 - Existing upstart script was not working

### CODE REVIEW

**Comment by jahvi** [comment]
What's the difference between this and the previous implementation?

**Comment by badams** [comment]
@jahvi besides fixing the syntax error (stray `'`) it moved the main process outside of the **pre-start** section which was incorrect.

> pre-start script and post-stop script
Additional shell code can be given to be run before or after the binary or script specified with exec or  script. These are not expected to start the process, in fact, they can't. They are intended for preparing the environment and cleaning up afterwards. 

Having the main process in the pre-start section was causing the upstart script to hang and not execute correctly.

http://upstart.ubuntu.com/getting-started.html

**Comment by jahvi** [comment]
Thanks for the explanation, I have 0 experience with upstart

**Comment by fideloper** [comment]
Whoops, thank you!

**Pull request merged**
