### PR TITLE
Adding installer for WP-CLI

### PR DESCRIPTION
**Pull request by louy**

### CODE REVIEW

**Comment by fideloper** [comment]
Howdy!

Thanks for the contribution. I think the only thing missing are updates to the readme.sh (and maybe the gh docs branch if you want to go that far :D )

**Comment by louy** [comment]
@fideloper Could you take another look?

**Comment by andrewtch** [comment]
Not the best way, imho. You should check for wp-cli existence and try to update it.

**Comment by andrewtch** [comment]
However, @fideloper , this PR is senseless since this can be installed through composer:

"wp-cli/wp-cli=*"

Imho, there's not need to install composer packages separately.

**Comment by louy** [comment]
Well @andrewtch, there was no composer profile when I created this.
I'm not sure whether you want it or not. I'm honestly not using this at all. I'm not a fan of Vagrant.

**Comment by andrewtch** [comment]
I suggest closing this.

**Pull request closed without merging**
