### PR TITLE
Fix for changed PHP PPA repository

### PR DESCRIPTION
**Pull request by Repox**
This pull request addresses issue #568 and #569

### CODE REVIEW

**Comment by Repox** [comment]
If someone wants to start using the fix, change the `Vagrantfile`'s Github config settings to the following:

    # Config Github Settings
    github_username = "Repox"
    github_repo     = "Vaprobash"
    github_branch   = "feature/phpppa"
    github_url      = "https://raw.githubusercontent.com/#{github_username}/#{github_repo}/#{github_branch}"

Currently, the available PHP versions are:

- 5.5
- 5.6
- 7.0
- 7.1

**Comment by bendubuisson** [comment]
Any chance of merging this PR please? been using Repox's fix in the mean time but it would be good to go back to "normal". @fideloper 

Thanks!

**Comment by Repox** [comment]
I now you're busy, @fideloper , but it would be nice with some feedback on this.

It's hard to recommend Vaprobash in it's current state.

**Comment by edwinveldhuizen** [comment]
@fideloper please merge this pull request 😊

**Comment by fideloper** [comment]
Does look good, let's try it out. 

In theory this entire thing should go to Ubuntu 16.04 version of this, but I don't have time to put the work into that unfortunately.

**Comment by Repox** [comment]
Thank you. 

I'll take a look at bumping it to 16.04.

**Comment by bendubuisson** [comment]
5.5 is still broken (5.6 works)
```
vagrant@php55:~$ sudo apt-get install php5.5-cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php5.5-cli
E: Couldn't find any package by regex 'php5.5-cli'
```

**Comment by bendubuisson** [comment]
from https://launchpad.net/~ondrej/+archive/ubuntu/php:

```
PLEASE DON'T USE PHP 5.4 OR PHP 5.5. The PHP 5.5 and later are no longer supported with security updates, therefore they are not included in this repository.
```

**Comment by Repox** [comment]
At the time when I created the pull request, 5.5 worked, but I do see that this isn't the case anymore. 

I'll have to update the documentation accordingly.

**Pull request merged**
