### PR TITLE
Kibana (for elastic search) installation script

### PR DESCRIPTION
**Pull request by nathanmac**

### CODE REVIEW

**Comment by connerbw** [comment]
Thanks for this.

PS: Shouldn't you modify the Vagrantfile as well?

**Comment by nathanmac** [comment]
@connerbw modify what in the Vagrantfile, ports?

**Comment by connerbw** [comment]
@nathanmac I mean there is no corresponding commented out Vagrantfile entry. Example:

```ruby
  # Install Elasticsearch
  # config.vm.provision "shell", path: "#{github_url}/scripts/elasticsearch.sh"
```

**Comment by nathanmac** [comment]
@connerbw - I missed that thanks, updated now

**Comment by fideloper** [comment]
Thanks!

**Pull request merged**
