### PR TITLE
Added RabbitMQ script

### PR DESCRIPTION
**Pull request by Intrepidity**
Added an installer for RabbitMQ. This fixes issue #409

### CODE REVIEW

**Comment by fideloper** [comment]
Sweet, thanks!

Is there a stable deb to use over the development one added in this PR?
(I'm on the go right now but can check later).

**Comment by fideloper** [comment]
Actually I see the deb appears to be "testing" - I'm not sure what that
means in terms of RabbitMQ.

**Comment by Intrepidity** [comment]
There's only a testing one as far as I know and can see. They do not want to give support on binaries, and want you to compile the thing yourself. Unfortunately my knowledge isn't good enough to write a script for this. If the policy is to only accept stable releases then feel free to decline the PR.

**Comment by fideloper** [comment]
Thanks! Now that I"m back in front of a computer, I can see that their docs only mention the "testing" one as well.

Funny... "testing" vs..."kitten"... http://www.rabbitmq.com/debian/dists/

**Comment by fideloper** [comment]
This hardly makes sense but is the explanation on that: http://hg.rabbitmq.com/rabbitmq-server/raw-annotate/aed114148888/packaging/debs/apt-repository/README-real-repository

Let's go with "testing" for now!

**Comment by fideloper** [comment]
Thanks!

**Pull request merged**
